"""A null model for AUROC, and the multiplicity correction the tables need.

Every AUROC in this repository carries a percentile bootstrap interval from
`detect.auroc_ci` and nothing else. A bootstrap interval describes the sampling
variability of an estimate; it is not a test against a null hypothesis, and a
reader who sees 0.61 [0.53, 0.69] still has to supply the null by eye. This
module supplies it explicitly, by permutation.

The second gap is multiplicity. An experiment here reports four relations times
three metrics, and twelve AUROCs read by eye will show one "significant" result
at the 0.05 level about half the time under a complete null. `holm` is the
step-down correction that removes that reading, and it is deliberately the
conservative one: Holm controls the family-wise error rate under arbitrary
dependence between the tests, which matters because the three metrics are
computed from the same answers and are not independent.
"""

from __future__ import annotations

import numpy as np

from .detect import auroc

__all__ = ["permutation_auroc", "holm"]


def permutation_auroc(
    scores: np.ndarray, labels: np.ndarray, n_perm: int = 10000, seed: int = 0
) -> tuple[float, float]:
    """Observed AUROC and a one-sided permutation p-value against a label null.

    The null is generated by shuffling `labels` and recomputing AUROC with
    `detect.auroc`, so the null distribution inherits the exact tie handling,
    class balance and sample size of the observed data rather than an asymptotic
    approximation of them.

    **One-sided, and why.** Scores in this repository are oriented so that
    "predicting WRONG" scores above 0.5 — `max_softmax_score` is `1 - p`,
    `logit_margin` is negated, `symmetry_scores` ranks collision upward. A
    detector that lands below 0.5 is not a detector reading backwards, it is a
    detector that failed, and counting it as evidence would let a score that
    anti-predicts the label be reported as a hit. The p-value therefore counts
    only null AUROCs at or above the observed one.

    **The `+1`.** The estimator is `(1 + #{null >= observed}) / (1 + n_perm)`,
    which cannot return 0. This is not a fudge: `n_perm` draws can resolve a tail
    no finer than `1 / (1 + n_perm)`, so an exact zero would claim more
    resolution than the computation has. The floor is reported honestly instead,
    and a smaller p-value requires more permutations, not a different formula.

    **Exchangeability caveat — read before quoting the number.** The collision
    half of `regime.symmetry_scores` is a deterministic function of the SHARED
    orbit partition: an entity's collision score is the fraction of OTHER
    entities receiving its answer. Per-entity scores are therefore not
    independent, and moving one entity's answer changes every other entity's
    score. This test permutes labels against a FIXED score vector, so it is a
    test of the association between the scores and the labels under exchangeable
    label assignment, and nothing more.

    What the p-value licenses: the claim that this score vector orders these
    labels better than a random relabelling of these same entities would.

    What it does not license: treating the entities as independent draws,
    generalising to a fresh entity set, or reading the p-value as a statement
    about the detector's population AUROC. For the latter, `detect.auroc_ci` is
    still the right instrument, and it carries its own dependence caveat.

    Args:
        scores: per-item scores, higher meaning more likely positive.
        labels: 1 for the positive class (here: the answer was wrong).
        n_perm: number of label shuffles. Runtime is linear in this.
        seed: seed for `np.random.default_rng`; results are exactly reproducible.

    Returns:
        `(observed_auroc, p_value)`.

    Raises:
        ValueError: if the shapes disagree, if `n_perm` is not positive, or if
            either class is empty — AUROC is a constant 0.5 then, and the test
            would silently return p = 1.0 for every input.
    """
    scores = np.asarray(scores, dtype=np.float64).ravel()
    labels = np.asarray(labels).ravel().astype(bool)
    if scores.shape != labels.shape:
        raise ValueError(f"scores and labels must have equal length; got {scores.shape} and {labels.shape}")
    if scores.size == 0:
        raise ValueError("scores must be non-empty")
    if not np.all(np.isfinite(scores)):
        raise ValueError("scores must be finite; got NaN or inf")
    n_pos = int(labels.sum())
    if n_pos == 0 or n_pos == len(labels):
        raise ValueError(f"both classes must be present; got {n_pos} positives of {len(labels)}")
    if n_perm < 1:
        raise ValueError(f"n_perm must be positive; got {n_perm}")

    observed = auroc(scores, labels)
    rng = np.random.default_rng(seed)
    permuted = labels.copy()
    n_ge = 0
    for _ in range(n_perm):
        rng.shuffle(permuted)
        if auroc(scores, permuted) >= observed:
            n_ge += 1
    return observed, (1.0 + n_ge) / (1.0 + n_perm)


def holm(pvalues: np.ndarray) -> np.ndarray:
    """Holm-Bonferroni step-down correction, returned in the INPUT order.

    With `k` p-values sorted ascending, the `j`-th smallest (0-indexed) is
    multiplied by `k - j`, the running maximum is taken so the sequence is
    monotone non-decreasing, and the result is clipped to 1.0. Returning the
    corrected values in sorted order rather than the caller's order is the
    classic implementation bug — it silently reassigns each relation's p-value to
    a different relation — so the inverse permutation is applied here and pinned
    by a test.

    Holm controls the family-wise error rate under arbitrary dependence, which is
    the relevant guarantee: the metrics compared in these tables are computed
    from the same model answers, so an assumption of independence between them
    would be false.

    Raises:
        ValueError: if the input is not one-dimensional, is empty, or contains
            values outside [0, 1] or non-finite entries.
    """
    p = np.asarray(pvalues, dtype=np.float64).ravel()
    if np.asarray(pvalues).ndim > 1:
        raise ValueError(f"pvalues must be one-dimensional; got shape {np.asarray(pvalues).shape}")
    if p.size == 0:
        raise ValueError("pvalues must be non-empty")
    if not np.all(np.isfinite(p)):
        raise ValueError("pvalues must be finite; got NaN or inf")
    if np.any(p < 0.0) or np.any(p > 1.0):
        raise ValueError(f"pvalues must lie in [0, 1]; got range [{p.min()}, {p.max()}]")

    k = p.size
    order = np.argsort(p, kind="mergesort")
    adjusted = np.maximum.accumulate(p[order] * np.arange(k, 0, -1))
    out = np.empty(k, dtype=np.float64)
    out[order] = np.minimum(adjusted, 1.0)
    return out
